### PR TITLE
Add email alerts to Research and Statistics Finder

### PR DESCRIPTION
**Pull request by hannako**
https://trello.com/c/jh8yogol/955-add-more-email-alerts-to-the-research-and-statistics-finder

### CODE REVIEW

**Comment by theseanything** [comment]
Could we give this draft PR a meaningful title?

**Comment by hannako** [comment]
Sure thing! Just opened it up before dashing to a meeting to get the CI to start running :-)

**Comment by benthorner** [comment]
@hannako just looking through the PRs and tidying up. Do you want to keep this open?

**Comment by hannako** [comment]
thanks for the nudge @benthorner!

**Pull request closed without merging**
