### PR TITLE
Add more examples to the PR template

### PR DESCRIPTION
**Pull request by andysellick**
Adding a few more useful example links to add to the PR template.

---

## Search page examples to sanity check:

- http://finder-frontend-pr-1234.herokuapp.com/search/all
- http://finder-frontend-pr-1234.herokuapp.com/search/research-and-statistics
- http://finder-frontend-pr-1234.herokuapp.com/search/news-and-communications?parent=%2Feducation&topic=c58fdadd-7743-46d6-9629-90bb3ccc4ef0
- http://finder-frontend-pr-1234.herokuapp.com/drug-device-alerts
- http://finder-frontend-pr-1234.herokuapp.com/find-eu-exit-guidance-business
- http://finder-frontend-pr-1234.herokuapp.com/find-eu-exit-guidance-business?parent=&keywords=eori&order=relevance
- http://finder-frontend-pr-1234.herokuapp.com/find-eu-exit-guidance-business?parent=&keywords=&sector_business_area%5B%5D=aerospace&order=topic
- http://finder-frontend-pr-1234.herokuapp.com/uk-nationals-living-eu
- http://finder-frontend-pr-1234.herokuapp.com/prepare-business-uk-leaving-eu

[Other finders](https://live-stuff.herokuapp.com/finders)

### CODE REVIEW

**Comment by andysellick** [comment]
> I'd prefer we keep the URLs intact, it makes them easier to edit + see what you're clicking on.

Yeah, fair point. I wanted to explain why some of the ones that look similar are there. Is there a way of having the URLs but still keeping the descriptions? Maybe

- Grouped results: http://finder-frontend-pr-1234.herokuapp.com/find-eu-exit-guidance-business

**Comment by bilbof** [comment]
That sounds fine. a shame Github doesn't allow one access to pull request variables :D

**Comment by andysellick** [comment]
@bilbof I've changed it back.

**Comment by andysellick** [comment]
> Might be nice to strip out the empty params in the new examples, but I approve otherwise 👍

Done, thanks.

**Pull request merged**
