### PR TITLE
Update to Ruby 3.1.2.

### PR DESCRIPTION
**Pull request by sengi**
- Update Ruby from 2.7.6 to 3.1.2. (3.1.3 is not available yet on govuk-puppet.)
- Update all dependencies (within existing constraints), since current versions are less likely to have compatibility bugs with Ruby 3.
- Fix auto-correctable rubocop errors for the new Ruby version.
- Fix tests to work with Ruby 3.1.

Deployment: requires `deploy:with_hard_restart` on the EC2 environments.

### CODE REVIEW

**Comment by sengi** [comment]
See https://github.com/alphagov/content-data-admin/pull/1155#issuecomment-1382742972 re failing test.

**Comment by sengi** [comment]
PTAL. We have to call time on Ruby 2.7 now since we're starting to run into compatibility issues, e.g. Brakeman is dropping support for it.

**Review by ChrisBAshton — APPROVED** [review]
LGTM 👍 Could you also revert e5444df24519cab589d07727dcb6a85ae59b2cfc as part of this PR?

**Comment by sengi** [comment]
> LGTM 👍 Could you also revert [e5444df](https://github.com/alphagov/finder-frontend/commit/e5444df24519cab589d07727dcb6a85ae59b2cfc) as part of this PR?

Sure. Done!

**Comment by sengi** [comment]
I'll merge on Monday.

**Comment by sengi** [comment]
Rebased to fix merge conflict.

**Pull request merged**
