### PR TITLE
Make facet parser accept text facets

### PR DESCRIPTION
**Pull request by tommyp**
With the changes in 04fcb52d we need to make this App work with both `text` and `multi-select` while we deploy them.

### CODE REVIEW

**Comment by tommyp** [comment]
Updated the commit to fix some broken tests.

**Comment by evilstreak** [comment]
If we deployed just this it would stop working – it needs the schema to be updated to include `filterable: true` to maintain functionality.

We need to default `filterable` to true to get it backwards compatible.

**Comment by tommyp** [comment]
I thought we were deploying https://github.com/alphagov/specialist-publisher/pull/392 first? Or should I make them as independent from each other as I can?

**Comment by tommyp** [comment]
Added some more code to make this more resilient against the _old_ versions of the schemas.

**Pull request merged**
